laravel/routes/web.php
<?php
Route::get('/', 'WebPageController@index')->name('u_home');

Route::get('/about', 'WebPageController@about')->name('about');

// Route::get('/about', 'WebPageController@about')->name('about');

Route::get('/achievements/{type?}', 'WebPageController@achievements')->name('achievements');

Route::get('/upcoming-batch/{type?}', 'WebPageController@upcomingBatch')->name('upcoming-batch');

Route::get('/gallery/{type?}', 'WebPageController@gallery')->name('gallery');

Route::get('/faqs/{type?}', 'WebPageController@faqs')->name('faqs');

Route::get('/smart-study/{type?}', 'WebPageController@smartStudy')->name('smart-study');

Route::get('/downloads/{type?}', 'WebPageController@downloads')->name('downloads');

Route::get('/course-pricing/{type?}', 'WebPageController@coursePrices')->name('course-pricing');

Route::get('/lecture-videos/{type?}', 'WebPageController@lectureVideos')->name('lecture-videos');

Route::get('/contact', 'WebPageController@contacts')->name('contact');

Route::get('/blogs', 'WebPageController@blogs')->name('blogs');

Route::get('/checkout/{id}','OrderController@checkout')->name('checkout');

Route::post('/placeorder','OrderController@getPay')->name('placeorder');	

Route::post('/paystatus','OrderController@orderStatus')->name('orderStatus');

Route::get('/booked/order/{id}/{status?}', 'OrderController@previous')->name('previous');


Route::get('/dashboard', function () {
	return view('samples.dashboard');
});

Route::get('/table', function () {
	return view('samples.table');
});
Route::get('/form', function () {
	return view('samples.form');
});
Route::get('/d-login', function () {
	return view('common.login');
});




Route::group(['prefix' => 'candidate'], function() {
	
	Route::group(['prefix' => 'test'], function() {

		Route::get('/register', function () {
			return view('candidates.register');
		});
		Route::get('/login', 'StudentController@index');
		
	});

});

Route::group(['prefix' => 'candidate', 'middleware' => 'candidate', 'as' => 'candidate.'], function() {

	Route::group(['prefix' => 'test', 'as' => 'test.'], function() {

		Route::get('/', 'StudentController@home')->name('c_home');
		
		Route::get('/start/{id}', 'TestController@start')->name('start');
		
		Route::get('/startTest', 'TestController@startTest')->name('startTest');
		
		Route::get('test', 'TestController@index')->name('student.test');

		Route::post('test', 'TestController@store')->name('send-test');
		
		Route::get('/finish', 'TestController@finish')->name('finish');
		
		Route::get('/solution/{id}', 'TestController@solution')->name('solution');
		// Route::get('/solution/{id}', 'StudentController@solution')->name('solution');
		
	});
	Route::post('/searchMobile', 'StudentController@searchMobile');		

	Route::get('package-can-test/{id}', 'PackageController@getCanTest')->name('pack-can-test');

});

Route::resource('test', 'TestController');

Route::resource('candidate', 'CandidateController');

Route::resource('client', 'ClientController');

Route::post('checkEmail', 'ClientController@checkEmail');

Route::post('addBType', 'ClientController@addBType');

Route::resource('degree', 'DegreeController');

Route::resource('question', 'QuestionController');

Route::group(['prefix' => 'admin', 'as' => 'admin.'], function() {

	// Route::get('/register', function () {
	// 	return view('candidates.register');
	// });
	Route::get('/login', 'AdminController@login')->name('login');


});
Route::get('get-chart', 'TestController@getChart')->name('get-chart');
Route::group(['prefix' => 'admin', 'middleware' => 'admin', 'as' => 'admin.'],function (){

	Route::get('/', 'AdminController@index')->name('home');

	Route::get('/student/create', 'StudentController@create');

	Route::get('/student/edit/{id}', 'StudentController@edit');

	Route::post('/student/edit', 'StudentController@update');

	Route::post('/student/create', 'StudentController@store');

	Route::post('/searchMobile', 'StudentController@searchMobile');

	Route::resource('question', 'QuestionController');
	
	Route::get('add-question/{sub}/{test}', 'QuestionController@addQuestion')->name('add-question');

	Route::get('all-test', 'AdminController@allTest')->name('all-test');
		
	
	Route::get('subjects/{id}', 'AdminController@subjects')->name('subjects');
	
	Route::resource('subject', 'SubjectController');
	
	Route::get('results', 'AdminController@results')->name('result');

	Route::get('test-result/{id}', 'AdminController@result');
	
	Route::get('all-candidates', 'AdminController@allCandidates')->name('all-candidates');
	// Route::get('all-candidates', 'AdminController@allCandidates')->name('all-candidates');
	// purchases
	Route::get('all-questions/{sub}/{test}', 'AdminController@allQuestions')->name('all-questions');
	
	Route::resource('test', 'TestController');

	Route::resource('package', 'PackageController');
	
	Route::resource('purchase', 'PurchaseController');

	Route::get('package-test/{id}', 'PackageController@getTest')->name('pack-test');

	Route::post('/batch', 'AdminController@storeBatch');

	Route::resource('achievement', 'AchievementController');

	Route::resource('upcoming-batch', 'UpcomingBatchController');
	
	Route::resource('gallery', 'GalleryController');
	
	Route::resource('faq', 'FaqController');
	
	Route::resource('smart-study', 'SmartStudyController');
	
	Route::resource('download', 'DownloadController');

	Route::resource('blog', 'BlogController');
	
	Route::resource('testimonial', 'TestimonialController');

	Route::resource('banner', 'BannerController');

	Route::resource('lecture', 'LectureController');
	
	Route::resource('whats-new', 'WhatsNewController');
	
	Route::resource('enquiry', 'EnquiryController');

	Route::get('ach-type', 'AchievementController@achType')->name('ach-type');

});



// Route::resource('/record', 'RecordController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// Route::post('/getDatatable', 'CandidateController@getDataTable');

Route::post('/getClients', 'ClientController@getClients');

Route::post('/getClientData', 'ClientController@getClientData');

Route::get('/getRemarkBox/{id}', 'ClientController@getRemarkBox');



Route::get('/getStatus', 'CandidateController@getStatus');

Route::get('/getAllRemarks/{id}', 'ClientController@getAllRemarks');

Route::get('/getAllMobile/{id}', 'ClientController@getAllMobile');

Route::post('/designation', 'CandidateController@storeDes');

Route::get('/getFixed', 'ClientController@fixTable');

Route::group(['middleware' => 'auth'], function(){
	Route::get('/getCandidates', 'CandidateController@getCandidates')->name('getCandidates');	
	Route::get('/excel',function(){return view('excel');});

	Route::post('/ExcelUpload','CandidateController@importExcel');
});
Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

laravel/resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Sungare | @yield('title')</title>

    <link href="{{ asset('css/style.css') }}" rel="stylesheet">
    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('font-awesome/css/font-awesome.min.css') }}" rel="stylesheet">

    @stack('header')
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="#">
                        Sungare
                    </a>
                </div>
                @if (Route::currentRouteName() == "test.index")
                <div class="timer-div" id = "ms_timer"></div>
                @endif
                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">

                        @if (Route::currentRouteName() != "test.index")



                        @if (Auth::guest())
                        <li><a href="{{ route('login') }}">Login</a></li>
                        {{-- <li><a href="{{ route('register') }}">Register</a></li> --}}
                        @else
                        @if (Auth::user()->type == 4)
                        <li><a href="{{ url('client') }}">View CLients</a><span class="count cli-pos hidden" id ="canCount"></span></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                Clients <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu" role="menu">
                                <li>
                                    <a href="{{ url('excel') }}">Upload Excel</a>
                                </li>
                                <li>
                                    <a href="{{ route('client.create') }}">Add Single record</a>
                                </li>
                                <li>
                                    <a href="{{ url('getFixed') }}">Fix Data</a>
                                </li>
                            </ul>
                        </li>    
                        @else

                        <li><a href="{{ url('candidate') }}">View Candidates</a><span class="count can-pos hidden" id ="canCount"></span></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                Candidates <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu" role="menu">
                                <li>
                                    <a href="{{ url('excel') }}">Upload Excel</a>
                                </li>
                                <li>
                                    <a href="{{ route('candidate.create') }}">Add Single record</a>
                                </li>
                            </ul>
                        </li>
                        @endif
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu" role="menu">
                                <li>
                                    <a href="{{ route('logout') }}"
                                    onclick="event.preventDefault();
                                    document.getElementById('logout-form').submit();">
                                    Logout</a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        {{ csrf_field() }}
                                    </form>
                                </li>
                            </ul>
                        </li>

                        @endif
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
    {{-- <script src="{{ asset('js/jquery-3.2.1.min.js') }}"></script> --}}
    <script type="text/javascript">
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
        type = {{Auth::guest() ? '0' : Auth::user()->type}}
    </script>
    <script>

        $url = "{{Request::ip() != '127.0.0.1' ? '/data/':'/'}}";

    </script>
    @stack('footer')
    <script type="text/javascript" src = "{{ asset('js/footer.js') }}"></script>
    @stack('last')
</body>
</html>

laravel/resources/views/layouts/footer.blade.php
<footer class="footer">
	<div class="container-fluid">
		{{-- <nav class="pull-left">
			<ul>
				<li>
					<a href="#">
						Home
					</a>
				</li>
				<li>
					<a href="#">
						Company
					</a>
				</li>
				<li>
					<a href="#">
						Portfolio
					</a>
				</li>
				<li>
					<a href="#">
						Blog
					</a>
				</li>
			</ul>
		</nav> --}}
		<p class="copyright text-center">
			&copy;
			<script>
				document.write(new Date().getFullYear())
			</script>
			, Designed and Developed by <a href="http://www.sungare.com">Sungare Technologies Pvt. Ltd.</a>
		</p>
	</div>
</footer>
</div>
</div>
</body>
<!--   Core JS Files   -->
<script src="{{ asset('assets/js/jquery-3.2.1.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('assets/js/bootstrap.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('assets/js/material.min.js') }}" type="text/javascript"></script>
<!--  PerfectScrollbar Library -->
<script src="{{ asset('assets/js/perfect-scrollbar.jquery.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/quill.js') }}"></script>

<!-- Material Dashboard javascript methods -->
<script src="{{ asset('assets/js/material-dashboard.js?v=1.2.0') }}"></script>
<script type="text/javascript" src="{{ asset('js/jquery-ui.min.js') }}"></script>
<script type="text/javascript">
	var mainUrl = '{{ route('u_home') }}/';
</script>
<script type="text/javascript" src="{{ asset('js/crud.js') }}"></script>

<script type="text/javascript">
	// $.ajaxSetup({
	// 	headers: {
	// 		'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
	// 	}
	// });
	type = {{Auth::guest() ? '0' : Auth::user()->type}};

	$url = "{{Request::ip() != '127.0.0.1' ? '/admin':'/'}}";
	var rootPath = "{{ route('admin.home') }}/";
</script>
@stack('footer')
{{-- <script type="text/javascript" src = "{{ asset('js/footer.js') }}"></script> --}}
<script type="text/javascript">
	$('#hide').on({
		'click': function () {
			$('.sidebar').toggle('slide');
			$('.main-panel').css('width','100%');
			$(this).toggle('slide');
			$('#show').toggle('slide');
			// $('html').addClass('nav-open');
		}
	});
	$('#show').on({
		'click': function () {
			$('.sidebar').toggle('slide');			
			$('.main-panel').css('width','calc(100% - 260px)');
			
			$(this).toggle('slide');
			$('#hide').toggle('slide');			
			// $('html').addClass('nav-open');
		}
	});
	// var all = $('.sidebar-wrapper li a').attr('href');
	// console.log(all);
	@php		
	$check = [route('admin.home'),route('admin.package.create'), route('admin.test.create'), route('admin.all-test'), route('admin.result')];
	if(in_array(\Request::fullUrl(), $check)){
		\Request::session()->put('page', \Request::fullUrl());
	}
	@endphp
	var current = '{{ \Request::session()->get('page') }}';	
	$('.sidebar-wrapper li').each(function(k,v){
		var curl = $(v).find('a').attr('href');
		$(v).addClass((curl == current) ? 'active' : '');
	});

	// $('.sidebar-wrapper ul.nav > li').not("ul li ul li").each(function(k,v){
	// 	var curl = $(v).find('a').attr('href');
	// 	console.log(v);
	// 	$(v).addClass((curl == current) ? 'active' : '');
	// });
	$(window).on('load',function(){
		$('#loader').addClass('hidden');
	});
</script>
@stack('last')
</html>

laravel/resources/views/layouts/header.blade.php
<!doctype html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="icon" type="image/png" href="{{ asset('images/fav-icon.png') }}" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	
	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
	<meta name="viewport" content="width=device-width" />
	<meta name="csrf-token" content="{{ csrf_token() }}">
	<style type="text/css">
		.loader{		
			position: fixed;
			z-index: 111111;
			background: #eee;
			width: 100%;
			text-align: center;
			height: 1000px;
			padding-top: 15%;
		}		
	</style>
	<title>{{ config('app.name') }} | @yield('title')</title>

	<link href="{{ asset('css/style.css') }}" rel="stylesheet">
	<!-- Bootstrap core CSS     -->
	<link href="{{ asset('assets/css/bootstrap.min.css') }}" rel="stylesheet" />
	<!--  Material Dashboard CSS    -->
	<link href="{{ asset('assets/css/material-dashboard.css?v=1.2.0') }}" rel="stylesheet" />
	<!--  CSS for Demo Purpose, don't include it in your project     -->
	{{-- <link href="{{ asset('assets/css/demo.css') }}" rel="stylesheet" /> --}}

	<link href="{{ asset('font-awesome/css/font-awesome.min.css') }}" rel="stylesheet">	
    <link rel="stylesheet" type="text/css" href="{{ asset('css/quill.snow.css') }}">
	@stack('header')
	<!--     Fonts and icons     -->
	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
	<link href='https://fonts.googleapis.com/css?family=Roboto:400,700,300|Material+Icons' rel='stylesheet' type='text/css'>
	
</head>

<body>

	<div class="loader" id = "loader">
		<img src="{{ asset('images/logo.png') }}" width = "120">
		<p style="margin-top:10px;">Loading...</p>
	</div>

laravel/resources/views/layouts/sidebar.blade.php
@include('layouts.header')
<div class="wrapper">
	<div id = "hide">
		<i class="material-icons">reorder</i>
	</div>
	<div id = "show">
		<i class="material-icons">reorder</i>
	</div>
	<div class="sidebar" data-color="blue" data-image="{{ asset('images/logo.png') }}">
		<div class="logo">
		{{-- 	<a href="http://www.creative-tim.com" class="simple-text">
				Creative Tim
			</a> --}}
			<a href="{{ url('/admin') }}">
				<img src="{{ asset('images/logo.png') }}">
			</a>
		</div>
		<div class="sidebar-wrapper">
			<ul class="nav">
				<li>
					<a href="{{ route('admin.home') }}">
						<i class="material-icons">dashboard</i>
						<p>Dashboard</p>
					</a>
				</li>				
				<li>
					<a href="#">
						<i class="material-icons">library_books</i>
						<p>Package</p>
					</a>
					<ul class="submenu">
						<li><a href="{{ route('admin.package.index') }}">Package List</a></li>
						<li><a href="{{ route('admin.package.create') }}">Create Package</a></li>
					</ul>
				</li>
				<li>
					<a href="#">
						<i class="material-icons">library_books</i>
						<p>Test</p>
					</a>
					<ul class="submenu">
						<li><a href="{{ url('/admin/all-test') }}">View Test</a></li>
						<li><a href="{{ route('admin.test.create') }}">Create Test</a></li>
					</ul>
				</li>
				<li>
					<a href="#">
						<i class="material-icons">library_books</i>
						<p>Candidates</p>
					</a>
					<ul class="submenu">
						<li><a href="{{ route('admin.all-candidates') }}">View Candidates</a></li>
						<li><a href="{{ url('/admin/results') }}">View Results</a></li>
					</ul>
				</li>
				<li>
					<a href="{{ route('admin.purchase.index') }}">
						<i class="material-icons">bubble_chart</i>
						<p>Purchases</p>
					</a>
				</li>
				<li>
					<a href="#">
						<i class="material-icons">library_books</i>
						<p>Achievement</p>
					</a>
					<ul class="submenu">
						<li><a href="{{ route('admin.achievement.create') }}">Create Achievement</a></li>
						<li><a href="{{ route('admin.achievement.index') }}">View Achievements</a></li>
					</ul>
				</li>
				<li>
					<a href="#">
						<i class="material-icons">library_books</i>
						<p>Upcoming Batches</p>
					</a>
					<ul class="submenu">
						<li><a href="{{ route('admin.upcoming-batch.create') }}">Create Upcoming Batch</a></li>
						<li><a href="{{ route('admin.upcoming-batch.index') }}">View Upcoming Batches</a></li>
					</ul>
				</li>
				<li>
					<a href="#">
						<i class="material-icons">library_books</i>
						<p>Galleries</p>
					</a>
					<ul class="submenu">
						<li><a href="{{ route('admin.gallery.create') }}">Create Gallery</a></li>
						<li><a href="{{ route('admin.gallery.index') }}">View Galleries</a></li>
					</ul>
				</li>
				<li>
					<a href="#">
						<i class="material-icons">library_books</i>
						<p>FAQ</p>
					</a>
					<ul class="submenu">
						<li><a href="{{ route('admin.faq.create') }}">Create FAQ</a></li>
						<li><a href="{{ route('admin.faq.index') }}">View FAQ</a></li>
					</ul>
				</li>
				<li>
					<a href="#">
						<i class="material-icons">library_books</i>
						<p>Smart Study</p>
					</a>
					<ul class="submenu">
						<li><a href="{{ route('admin.smart-study.create') }}">Create Smart Study</a></li>
						<li><a href="{{ route('admin.smart-study.index') }}">View Smart Study</a></li>
					</ul>
				</li>
				<li>
					<a href="#">
						<i class="material-icons">library_books</i>
						<p>Downloads</p>
					</a>
					<ul class="submenu">
						<li><a href="{{ route('admin.download.create') }}">Create Download</a></li>
						<li><a href="{{ route('admin.download.index') }}">View Downloads</a></li>
					</ul>
				</li>
				<li>
					<a href="#">
						<i class="material-icons">library_books</i>
						<p>Blogs</p>
					</a>
					<ul class="submenu">
						<li><a href="{{ route('admin.blog.create') }}">Create Blog</a></li>
						<li><a href="{{ route('admin.blog.index') }}">View Blogs</a></li>
					</ul>
				</li>		
				<li>
					<a href="#">
						<i class="material-icons">library_books</i>
						<p>Testimonial</p>
					</a>
					<ul class="submenu">
						<li><a href="{{ route('admin.testimonial.create') }}">Create Testimonial</a></li>
						<li><a href="{{ route('admin.testimonial.index') }}">View Testimonials</a></li>
					</ul>
				</li>		
				<li>
					<a href="#">
						<i class="material-icons">library_books</i>
						<p>Banners</p>
					</a>
					<ul class="submenu">
						<li><a href="{{ route('admin.banner.create') }}">Create Banner</a></li>
						<li><a href="{{ route('admin.banner.index') }}">View Banners</a></li>
					</ul>
				</li>
				<li>
					<a href="#">
						<i class="material-icons">library_books</i>
						<p>Lectures</p>
					</a>
					<ul class="submenu">
						<li><a href="{{ route('admin.lecture.create') }}">Create Lecture</a></li>
						<li><a href="{{ route('admin.lecture.index') }}">View Lectures</a></li>
					</ul>
				</li>
				<li>
					<a href="#">
						<i class="material-icons">library_books</i>
						<p>Whats New</p>
					</a>
					<ul class="submenu">
						<li><a href="{{ route('admin.whats-new.create') }}">Create Whats New</a></li>
						<li><a href="{{ route('admin.whats-new.index') }}">View Whats New</a></li>
					</ul>
				</li>
			</ul>
		</div>
	</div>
	<div class="main-panel">
		<nav class="navbar navbar-transparent navbar-absolute">
			<div class="container-fluid">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					{{-- <a class="navbar-brand" href="#"> Material Dashboard </a> --}}
				</div>
				<div class="collapse navbar-collapse">
					<ul class="nav navbar-nav navbar-right">
						{{-- <li>
							<a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">
								<i class="material-icons">dashboard</i>
								<p class="hidden-lg hidden-md">Dashboard</p>
							</a>
						</li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								<i class="material-icons">notifications</i>
								<span class="notification">5</span>
								<p class="hidden-lg hidden-md">Notifications</p>
							</a>
							<ul class="dropdown-menu">
								<li>
									<a href="#">Mike John responded to your email</a>
								</li>
								<li>
									<a href="#">You have 5 new tasks</a>
								</li>
								<li>
									<a href="#">You're now friend with Andrew</a>
								</li>
								<li>
									<a href="#">Another Notification</a>
								</li>
								<li>
									<a href="#">Another One</a>
								</li>
							</ul>
						</li> --}}
						<li>
							<a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">
								<i class="material-icons">person</i>
								{{ Auth::user()->name }}
							</a>
							<ul class="dropdown-menu">
								<li>
									<a href="{{ route('logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();">

										Logout
									</a>

									<form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
										{{ csrf_field() }}
									</form>
								</li>

							</ul>
						</li>
					</ul>
					{{-- <form class="navbar-form navbar-right" role="search">
						<div class="form-group  is-empty">
							<input type="text" class="form-control" placeholder="Search">
							<span class="material-input"></span>
						</div>
						<button type="submit" class="btn btn-white btn-round btn-just-icon">
							<i class="material-icons">search</i>
							<div class="ripple-container"></div>
						</button>
					</form> --}}
				</div>
			</div>
		</nav>
		<div class="content">
			@yield('content')
		</div>
		@include('layouts.footer')

laravel/resources/views/layouts/simple.blade.php
@include('layouts.header')
<div class="wrapper">
	<div class="logo">
		<a href="http://www.sungare.com" class="simple-text">
			<img src="{{ asset('images/logo.png') }}">
		</a>
	</div>
	<div class="content">
		@yield('content')
	</div>
	@include('layouts.footer')

laravel/resources/views/layouts/topbar.blade.php
@include('layouts.header')
<div class="wrapper">        
    <div class="main-panel" style="width: 100%!important;">
        <nav class="navbar navbar-transparent navbar-absolute">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class = "pad-left" href="{{ url('/candidate/test') }}"> 
                        <img src="{{ asset('images/fav-icon.png') }}" width = "70">
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li><div class="timer-div" id = "ms_timer"></div></li>
                        <li>
                            <a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="material-icons">person</i>
                                {{ Auth::user()->name }}

                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="{{ route('logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();">

                                        Logout
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        {{ csrf_field() }}
                                    </form>
                                </li>
                                
                            </ul>
                        </li>
                    </ul>                        
                </div>
            </div>
        </nav>
        <div class="content" style="margin-top: 50px!important;">

            @yield('content')

        </div>
        @include('layouts.footer')