laravel/routes/web.php
<?php
Route::get('/', 'WebPageController@index')->name('u_home');

Route::get('/about', 'WebPageController@about')->name('about');

// Route::get('/about', 'WebPageController@about')->name('about');

Route::get('/achievements/{type?}', 'WebPageController@achievements')->name('achievements');

Route::get('/upcoming-batch/{type?}', 'WebPageController@upcomingBatch')->name('upcoming-batch');

Route::get('/gallery/{type?}', 'WebPageController@gallery')->name('gallery');

Route::get('/faqs/{type?}', 'WebPageController@faqs')->name('faqs');

Route::get('/smart-study/{type?}', 'WebPageController@smartStudy')->name('smart-study');

Route::get('/downloads/{type?}', 'WebPageController@downloads')->name('downloads');

Route::get('/course-pricing/{type?}', 'WebPageController@coursePrices')->name('course-pricing');

Route::get('/lecture-videos/{type?}', 'WebPageController@lectureVideos')->name('lecture-videos');

Route::get('/contact', 'WebPageController@contacts')->name('contact');

Route::get('/blogs', 'WebPageController@blogs')->name('blogs');

Route::get('/checkout/{id}','OrderController@checkout')->name('checkout');

Route::post('/placeorder','OrderController@getPay')->name('placeorder');	

Route::post('/paystatus','OrderController@orderStatus')->name('orderStatus');

Route::get('/booked/order/{id}/{status?}', 'OrderController@previous')->name('previous');


Route::get('/dashboard', function () {
	return view('samples.dashboard');
});

Route::get('/table', function () {
	return view('samples.table');
});
Route::get('/form', function () {
	return view('samples.form');
});
Route::get('/d-login', function () {
	return view('common.login');
});




Route::group(['prefix' => 'candidate'], function() {
	
	Route::group(['prefix' => 'test'], function() {

		Route::get('/register', function () {
			return view('candidates.register');
		});
		Route::get('/login', 'StudentController@index');
		
	});

});

Route::group(['prefix' => 'candidate', 'middleware' => 'candidate', 'as' => 'candidate.'], function() {

	Route::group(['prefix' => 'test', 'as' => 'test.'], function() {

		Route::get('/', 'StudentController@home')->name('c_home');
		
		Route::get('/start/{id}', 'TestController@start')->name('start');
		
		Route::get('/startTest', 'TestController@startTest')->name('startTest');
		
		Route::get('test', 'TestController@index')->name('student.test');

		Route::post('test', 'TestController@store')->name('send-test');
		
		Route::get('/finish', 'TestController@finish')->name('finish');
		
		Route::get('/solution/{id}', 'TestController@solution')->name('solution');
		// Route::get('/solution/{id}', 'StudentController@solution')->name('solution');
		
	});
	Route::post('/searchMobile', 'StudentController@searchMobile');		

	Route::get('package-can-test/{id}', 'PackageController@getCanTest')->name('pack-can-test');

});

Route::resource('test', 'TestController');

Route::resource('candidate', 'CandidateController');

Route::resource('client', 'ClientController');

Route::post('checkEmail', 'ClientController@checkEmail');

Route::post('addBType', 'ClientController@addBType');

Route::resource('degree', 'DegreeController');

Route::resource('question', 'QuestionController');

Route::group(['prefix' => 'admin', 'as' => 'admin.'], function() {

	// Route::get('/register', function () {
	// 	return view('candidates.register');
	// });
	Route::get('/login', 'AdminController@login')->name('login');


});
Route::get('get-chart', 'TestController@getChart')->name('get-chart');
Route::group(['prefix' => 'admin', 'middleware' => 'admin', 'as' => 'admin.'],function (){

	Route::get('/', 'AdminController@index')->name('home');

	Route::get('/student/create', 'StudentController@create');

	Route::get('/student/edit/{id}', 'StudentController@edit');

	Route::post('/student/edit', 'StudentController@update');

	Route::post('/student/create', 'StudentController@store');

	Route::post('/searchMobile', 'StudentController@searchMobile');

	Route::resource('question', 'QuestionController');
	
	Route::get('add-question/{sub}/{test}', 'QuestionController@addQuestion')->name('add-question');

	Route::get('all-test', 'AdminController@allTest')->name('all-test');
		
	
	Route::get('subjects/{id}', 'AdminController@subjects')->name('subjects');
	
	Route::resource('subject', 'SubjectController');
	
	Route::get('results', 'AdminController@results')->name('result');

	Route::get('test-result/{id}', 'AdminController@result');
	
	Route::get('all-candidates', 'AdminController@allCandidates')->name('all-candidates');
	// Route::get('all-candidates', 'AdminController@allCandidates')->name('all-candidates');
	// purchases
	Route::get('all-questions/{sub}/{test}', 'AdminController@allQuestions')->name('all-questions');
	
	Route::resource('test', 'TestController');

	Route::resource('package', 'PackageController');
	
	Route::resource('purchase', 'PurchaseController');

	Route::get('package-test/{id}', 'PackageController@getTest')->name('pack-test');

	Route::post('/batch', 'AdminController@storeBatch');

	Route::resource('achievement', 'AchievementController');

	Route::resource('upcoming-batch', 'UpcomingBatchController');
	
	Route::resource('gallery', 'GalleryController');
	
	Route::resource('faq', 'FaqController');
	
	Route::resource('smart-study', 'SmartStudyController');
	
	Route::resource('download', 'DownloadController');

	Route::resource('blog', 'BlogController');
	
	Route::resource('testimonial', 'TestimonialController');

	Route::resource('banner', 'BannerController');

	Route::resource('lecture', 'LectureController');
	
	Route::resource('whats-new', 'WhatsNewController');
	
	Route::resource('enquiry', 'EnquiryController');

	Route::get('ach-type', 'AchievementController@achType')->name('ach-type');

});



// Route::resource('/record', 'RecordController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// Route::post('/getDatatable', 'CandidateController@getDataTable');

Route::post('/getClients', 'ClientController@getClients');

Route::post('/getClientData', 'ClientController@getClientData');

Route::get('/getRemarkBox/{id}', 'ClientController@getRemarkBox');



Route::get('/getStatus', 'CandidateController@getStatus');

Route::get('/getAllRemarks/{id}', 'ClientController@getAllRemarks');

Route::get('/getAllMobile/{id}', 'ClientController@getAllMobile');

Route::post('/designation', 'CandidateController@storeDes');

Route::get('/getFixed', 'ClientController@fixTable');

Route::group(['middleware' => 'auth'], function(){
	Route::get('/getCandidates', 'CandidateController@getCandidates')->name('getCandidates');	
	Route::get('/excel',function(){return view('excel');});

	Route::post('/ExcelUpload','CandidateController@importExcel');
});
Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

laravel/resources/views/admin/create-student.blade.php
@extends('layouts.sidebar')
@section('title')
Create New Student
@endsection
@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header" data-background-color="blue">
                    <h4 class="title">Create Student</h4>                  
                </div>
                <div class="card-content">
                    <div class="col-md-offset-2 col-md-8">

                        <form id = "candidateForm">
                            <div class="form-group label-floating ">
                                <label for="name" class="control-label">Name</label>

                             
                                    <input id="name" type="text" class="form-control" name="name" required autofocus>
                             
                            </div>

                            <div class="form-group label-floating ">
                                <label for="email" class="control-label">E-Mail Address</label>

                                
                                    <input id="email" type="email" class="form-control" name="email" required>
                                
                            </div>

                            <div class="form-group label-floating ">
                                <label for="mobile" class="control-label">Mobile</label>

                                
                                    <input id="mobile" type="text" class="form-control" name="mobile" required>

                                
                            </div>

                            <div class="form-group label-floating ">
                                <label for="alt-mobile" class="control-label">Parent Mobile</label>

                                
                                    <input id="alt-mobile" type="text" class="form-control" name="p_mobile" required>
                                
                            </div>

                            <div class="form-group label-floating ">
                                <label for="batch" class="control-label">Batch</label>
                                
                                    <select class="form-control" id = "batchSelection">
                                        <option>-Batch-</option>
                                        @forelse (App\Batch::get() as $batch)
                                        <option value="{{ $batch->batch_id }}">{{ $batch->batch_name }}</option>
                                        @empty

                                        @endforelse
                                        <option value = "other">Others</option>
                                    </select>
                                
                            </div>
                            <input type="hidden" name="batch" id = "batch">
                            <div class="form-group label-floating  hidden" id="batchOther">
                                
                                    <div class="input-group">
                                        <input type="text" class="form-control" id = "batchName">
                                        <div class="input-group-btn">
                                            <button id = "addBatch" class="btn btn-default" type="submit">
                                                Add
                                            </button>
                                        </div>
                                    </div>
                                    <div class="clearfix"></div>
                                    <div class="alert-warning batch-msg hidden" id = "batchMsg"></div>
                                
                            </div>

                            <input id="password" type="hidden" class="form-control" name="password" value = "{{ 'Can@'.(App\User::max('id')+1) }}">

                            <input type="hidden" name="type" value="102">
                            <div class="form-group label-floating ">
                                <div class="text-center">
                                    <button type="submit" class="btn btn-primary">
                                        Register
                                    </button>
                                </div>
                            </div>
                        </form>
                        <div class="alert alert-success text-center hidden" id = "candidateMessage"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('footer')

<script type="text/javascript" src = "{{ asset('js/candidate.js') }}"></script>
@endpush

laravel/resources/views/admin/create-test.blade.php
@extends('layouts.sidebar')
@section('title')
Create Test
@endsection
@push('header')
{{-- <link href="{{ asset('bootstrap/css/bootstrap.min.css') }}" rel="stylesheet" media="screen"> --}}
<link rel="stylesheet" type="text/css" href="{{ asset('css/bootstrap-datetimepicker.min.css') }}">
<link href="{{ asset('css/select2.css') }}" rel="stylesheet" />
@endpush
@section('content')
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<div class="card">
				<div class="card-header" data-background-color="blue">
					<h4 class="title">Create Test</h4>					
				</div>
				<div class="card-content">
					<div class="col-md-offset-2 col-md-8">
						<form id = "testForm">
							<div class="form-group label-floating">
								<label for="name" class="control-label">Test Title/Name</label>
								<input type="text" class="form-control" name="title" required>
							</div>
							<div class="form-group label-floating">
								<label for="pack" class="control-label">Package</label>
								@if ($pack)
								<input type="text" value="{{ $pack->pack_title }}" class="form-control" readonly disabled>
								<input type="hidden" value="{{ $pack->pack_id }}" class="form-control" name="package">
								@else
								<select name = "package" class="form-control" id = "batchSelection">
									<option value="-1">-Package-</option>
									@forelse (App\PackageDetail::get() as $pack)
									<option value="{{ $pack->pack_id }}" >{{ $pack->pack_title }}</option>
									@empty

									@endforelse
									<option value = "other">Others</option>
								</select>
								@endif
							</div>							
							<div class="form-group label-floating">
								<label for="name" class="control-label">Test Minutes</label>
								
								<input type="text" class="form-control" name="hours" required>								
							</div>
							<div class="form-group label-floating">
								<label for="name" class="control-label">Marks Pattern</label>
								
								<select class="form-control" name="pattern" id = "patternSelection">
									<option value="-1">Select</option>
									@forelse (App\MarkPattern::get() as $mark)
									<option value="{{ $mark->mark_id }}">{{ $mark->mark_title }}</option>								
									@empty
									@endforelse							
								</select>
								
							</div>
							<div class="form-group">
							    <label>Subject</label>
							    <select name = "subjects[]" class="form-control subjectDrop" multiple>
							        <option value = "-1">--select--</option>
							        @forelse (\App\Subject::get() as $sub)
							            <option value = "{{ $sub->sub_id }}">{{ $sub->sub_title }}</option>
							        @empty
							        @endforelse
							    </select>
							</div>
							<div class="form-group label-floating hidden" id="patternMark">
								<label for="name" class="control-label">Marks per Question</label>
								<input type="text" name = "score" id = "markBox" class="form-control">
							</div>
							<div class="form-group label-floating">
								<label for="name" class="control-label">Enable at </label>
								
								{{-- <input type="datetime" class="form-control" name="enable_at"> --}}
								<div class="input-group date form_datetime" id = "enableSelect" data-date="2017-01-1T05:25:07Z" data-date-format="dd MM yyyy - HH:ii p" data-link-field="enable">
									<input class="form-control" size="16" type="text" value="" readonly>
									<span class="input-group-addon">
										<span class="fa fa-calendar">
										</span>
									</span>
								</div>
								<input type="hidden" name="enable_at" id="enable" value="" />
								
							</div>
							<div class="form-group label-floating">
								<label for="name" class="control-label">Disable at </label>
								
								<div class="input-group date form_datetime" id = "disableSelect" data-date-format="dd MM yyyy - HH:ii p" data-link-field="disable">
									<input class="form-control" size="16" type="text" value="" readonly>
									<span class="input-group-addon">
										<span class="fa fa-calendar">
										</span>
									</span>
								</div>
								<input type="hidden" name="disable_at" id="disable" value="" />
								{{-- <input type="datetime" class="form-control" name="disable_at"> --}}
								
							</div>
							<div class="form-group label-floating">
								<div class="text-center">
									<button type="submit" name = "create-test" class="btn btn-primary">
										Create
									</button>
								</div>
							</div>
						</form>
						<div class="alert alert-success text-center hidden" id = "testMessage"></div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

@push('footer')

{{--	<script type="text/javascript" src="{{ asset('bootstrap/js/bootstrap.min.js') }}"></script>--}}
<script src="{{ asset('js/select2.min.js') }}"></script>
<script type="text/javascript" src = "{{ asset('js/bootstrap-datetimepicker.min.js') }}"></script>
{{-- <script type="text/javascript" src = "{{ asset('js/create-test.js') }}"></script> --}}
<script type="text/javascript">
	$('#patternSelection').on({
		'change' : function(){
			if(this.value == 1){
				$('#patternMark').removeClass('hidden');
				$('#markBox').attr('required', true);
			}else{
				$('#patternMark').addClass('hidden');
				$('#markBox').attr('required', false);
			}
		}
	});
	$('#testForm').CRUD({
		url : '{{ route('admin.test.store') }}',
		validation : false
	});
	var d = '{{ Carbon\Carbon::now('Asia/Kolkata') }}';
	$('#enableSelect').datetimepicker({
        //language:  'fr',
        weekStart: 1,
        todayBtn:  1,
        autoclose: 1,
        todayHighlight: 1,
        startView: 2,
        forceParse: 0,
        showMeridian: 1,
        startDate : d
    });
	$('#disableSelect').datetimepicker({
        //language:  'fr',
        weekStart: 1,
        todayBtn:  1,
        autoclose: 1,
        todayHighlight: 1,
        startView: 2,
        forceParse: 0,
        showMeridian: 1,
        startDate : d
    });
    function geturl(name) {
		var link = '{{ route('admin.home') }}/'+name;
		return link;
	}
	multiSelect('.subjectDrop', 'subject');
</script>
@endpush

laravel/resources/views/admin/create_blog.blade.php
@extends('layouts.sidebar')
@section('title')
Create FAQ
@endsection
@push('header')
@php
$ID = 'blog';
@endphp
<script>
    ID = '{{ $ID }}';
</script>
@endpush
@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header" data-background-color="blue">
                    <h4 class="title">Create {{ ucwords($ID) }}</h4>                  
                </div>
                <div class="card-content">
                    <div class="col-md-offset-2 col-md-8">
                        @include('admin.forms.blog_form')
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

laravel/resources/views/admin/create_lecture.blade.php
@extends('layouts.sidebar')
@section('title')
Create Lecture
@endsection
@push('header')
@php
$ID = 'lecture';
@endphp
<script>
    ID = '{{ $ID }}';
</script>
<style type="text/css">
#description{
    height: 200px;
}

</style>
{{-- <link href="{{ asset('bootstrap/css/bootstrap.min.css') }}" rel="stylesheet" media="screen"> --}}
<link rel="stylesheet" type="text/css" href="{{ asset('css/quill.snow.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('css/bootstrap-datetimepicker.min.css') }}">
@endpush
@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header" data-background-color="blue">
                    <h4 class="title">Create {{ ucwords($ID) }}</h4>                  
                </div>
                <div class="card-content">
                    <div class="col-md-offset-2 col-md-8">
                        @include('admin.forms.lecture_form')
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('footer')
<script type="text/javascript" src="{{ asset('js/quill.js') }}"></script>
<script type="text/javascript" src = "{{ asset('js/bootstrap-datetimepicker.min.js') }}"></script>
<script type="text/javascript">    
    var options = {      
        placeholder: 'Add Video description...',    
        theme: 'snow'
    };
    var description = new Quill('#description', options);

    route = "{{ route('admin.'.$ID.'.store') }}";

    $('#{{ $ID }}Form').CRUD({
        url : route,
        extraVariables : function(){
            return {'description' : document.querySelector(".ql-editor").innerHTML};
        },
        processResponse : function(data){
            
        },
        validation : false
    });
</script>
@endpush

laravel/resources/views/admin/results.blade.php
@extends('layouts.sidebar')
@section('title')
All Results
@endsection
@push('header')
<link rel="stylesheet" type="text/css" href="{{ asset('css/jquery.dataTables.min.css') }}">
@endpush
@section('content')
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<div class="card">
				<div class="card-header" data-background-color="blue">
					<h4 class="title">All Tests <a href = "{{ url('/admin') }}" class="btn btn-danger pull-right">Back</a></h4>                  
				</div>
				<div class="card-content">
					<table id = "table" class="table table-hover">
						<thead>
							<th style="width: 100px;">Title</th>
							<th>Package</th>
							<th>Duration</th>
							<th>Total Questions</th>
							<th>Created At</th>
							<th>Action</th>
						</thead>
						<tbody>
							@forelse ($tests as $test)				
							<tr>
								<td>{{ $test->test_title }}</td>
								<td>{{ $test->package->pack_title }}</td>
								<td>{{ $test->test_hours }} mins</td>
								<td>{{ \App\Question::where('qus_test_id',$test->test_id)->get()->count() }}</td>
								<td>{{ \Carbon\Carbon::parse($test->test_taken_at)->toFormattedDateString() }}</td>
								<td>
									<a href="{{ url('/admin/all-questions/'.$test->test_id) }}" class="btn btn-success">View Questions</a> | 
									{{-- <a href="#" class="btn btn-success">View Questions</a> |  --}}
									<a href="{{ url('/admin/test-result/'.$test->test_id) }}" class="btn btn-danger">See Result</a>
								</td>
							</tr>
							@empty
							{{-- empty expr --}}
							@endforelse
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection
@push('footer')
<script type="text/javascript">
	$(document).ready(function() {
		$('#table').DataTable();
	});
</script>
<script type="text/javascript" src = "{{ asset('js/jquery.dataTables.min.js') }}"></script>
@endpush

laravel/resources/views/admin/view_packages.blade.php
@extends('layouts.sidebar')
@section('title')
All Packages
@endsection
@push('header')
@php
$ID = 'package';
$ID2 = 'test';
@endphp
<link rel="stylesheet" type="text/css" href="{{ asset('css/bootstrap-datetimepicker.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('css/jquery.dataTables.min.css') }}">
<link href="{{ asset('admin-assets/datatables.net-bs/css/dataTables.bootstrap.min.css') }}" rel="stylesheet">
<link href="{{ asset('admin-assets/datatables.net-buttons-bs/css/buttons.bootstrap.min.css') }}" rel="stylesheet">
<link href="{{ asset('admin-assets/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css') }}" rel="stylesheet">
<link href="{{ asset('admin-assets/datatables.net-responsive-bs/css/responsive.bootstrap.min.css') }}" rel="stylesheet">
<link href="{{ asset('admin-assets/datatables.net-scroller-bs/css/scroller.bootstrap.min.css') }}" rel="stylesheet">
@endpush
@section('content')
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<div class="card">
				<div class="card-header" data-background-color="blue">
					<h4 class="title">All Packages<a href="{{ route('admin.package.create') }}" class="btn btn-danger pull-right">Add more Package</a></h4>					
				</div>
				<div class="card-content table-responsive">

					<table id = "{{ $ID }}Table" class="table table-hover">
						<thead>
							<th style="width: 100px;">Title</th>
							<th>Type</th>
							<th>Price</th>
							<th>Active On</th>
							<th>Deactive On</th>
							<th>Created</th>
							<th>Total Test</th>
							<th>Action</th>
						</thead>
						<tbody>
							@forelse ($packs as $pack)				
							<tr>
								<td>{{ $pack->pack_title }}</td>
								<td>{{ $pack->type->pt_title }}</td>
								<td align="right">{{ '&#8377;'.number_format($pack->pack_price) }}</td>
								<td>{{ Carbon\Carbon::parse($pack->pack_active_at)->format('jS M, Y g:i a') }}</td>
								<td>{{ Carbon\Carbon::parse($pack->pack_deactive_at)->format('jS M, Y g:i a') }}</td>
								<td>{{ Carbon\Carbon::parse($pack->pack_created_at)->format('jS M, Y g:i a') }}</td>
								<td><a href = "#" onclick = "fetch('{{ route('admin.pack-test',['id' => $pack->pack_id]) }}');" title = "Click to view all tests of {{ $pack->pack_title }} Package" class="btn btn-primary" >{{ $pack->test->count() }}</a></td>
								<td>
									<a href="{{ route('admin.package.edit', ['id' => $pack->pack_id]) }}" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Edit</a>
									<a onclick = "$(this).CRUD({id : '{{ $ID }}', url : '{{ route('admin.package.index') }}', pId : '{{ $pack->pack_id }}', name : '{{ $pack->pack_title }}'}, 'deleteForm');" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i> Delete </a>									
								</td>
							</tr>
							@empty
							<tr>
								<td colspan="8" class="text-center">
									No pack found, <a href="{{ route('admin.package.create') }}" class="btn btn-success">Create one NOW!!</a>
								</td>
							</tr>
							@endforelse
						</tbody>
					</table>
				</div>

				<!-- Test Modal -->
				<div id="{{ $ID2 }}Modal" class="modal fade" role="dialog">
					<div class="modal-dialog modal-lg">
						<!-- Modal content-->
						<div class="modal-content">
							<div class="modal-header">
								<button type="button" class="close" data-dismiss="modal">&times;</button>
								<h4 class="modal-title" id = "{{ $ID2 }}Title"></h4>
							</div>
							<div class="modal-body">
								<div class="table-responsive">

									<table id = "{{ $ID2 }}Table" class="table table-hover">
										<thead>
											<th style="width: 100px;">Title</th>
											<th>Duration</th>
											<th>Total Questions</th>
											<th>Created At</th>
											<th>Action</th>
										</thead>
										<tbody>
											
										</tbody>
									</table>

								</div>
							</div>
							<div class="modal-footer">
								<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
							</div>
						</div>

					</div>
				</div>
			</div>
		</div>
	</div>
</div>


<div class="modal fade" id="{{ $ID }}DModal" tabindex="-1" role="dialog" aria-labelledby="Modal" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header text-center">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title" id="myModalLabel">Are You Sure you want to delete <span id = "delName"></span> Pacakge ? It will delete all test and data realted to it</h4>
				<br>
				<div>
					<form id = "{{ $ID }}DForm">             
						<button type = "submit" class="btn btn-danger">Yes</button>
						<button type = "button" class="btn btn-success" data-dismiss="modal">No</button>
					</form>
				</div>            
			</div>
		</div>
	</div>
</div>
@endsection
@push('footer')
<script src="{{ asset('admin-assets/datatables.net/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('admin-assets/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
<script src="{{ asset('admin-assets/datatables.net-buttons/js/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('admin-assets/datatables.net-buttons-bs/js/buttons.bootstrap.min.js') }}"></script>
<script src="{{ asset('admin-assets/datatables.net-buttons/js/buttons.flash.min.js') }}"></script>
<script src="{{ asset('admin-assets/datatables.net-buttons/js/buttons.html5.min.js') }}"></script>
<script src="{{ asset('admin-assets/datatables.net-buttons/js/buttons.print.min.js') }}"></script>
<script type="text/javascript" src = "{{ asset('admin-assets/dataTables.buttons.min/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('admin-assets/dataTables.buttons.min/buttons.colVis.min.js') }}"></script>
<script src="{{ asset('admin-assets/datatables.net-keytable/js/dataTables.keyTable.min.js') }}"></script>
<script src="{{ asset('admin-assets/datatables.net-responsive/js/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('admin-assets/datatables.net-responsive-bs/js/responsive.bootstrap.js') }}"></script>
<script src="{{ asset('admin-assets/datatables.net-scroller/js/dataTables.scroller.min.js') }}"></script>
<script src="{{ asset('admin-assets/jszip/dist/jszip.min.js') }}"></script>
<script src="{{ asset('admin-assets/pdfmake/build/pdfmake.min.js') }}"></script>
<script src="{{ asset('admin-assets/pdfmake/build/vfs_fonts.js') }}"></script>
<script type="text/javascript" src = "{{ asset('js/bootstrap-datetimepicker.min.js') }}"></script>

<script type="text/javascript">	
	Table.init('{{ $ID }}');	
	Table.init('{{ $ID2 }}');
	function getUrl(id) {	
		return "{{ route('admin.test.create') }}?pack="+id;
	
	}	
	function fetch(route) {
		$('#{{ $ID2 }}Table').CRUD({
			url : route,
			processResponse: function(data){

				$('#{{ $ID2 }}Title').html(data.pack.pack_title+ ' Package Tests<a href="'+getUrl(data.pack.pack_id)+'" class="btn btn-danger pull-right">Add more Test</a>');
				$('#{{ $ID2 }}Modal').modal('toggle');
				$('#{{ $ID2 }}Table tbody').html(data.tr);			
			}
		}, 'get');
	}

	route = "{{ route('admin.'.$ID.'.store') }}";

	$('#{{ $ID }}Form').CRUD({
	    url : route,
	    validation : false
	});
	var d = '{{ Carbon\Carbon::now('Asia/Kolkata') }}';
	$('#enableSelect').datetimepicker({
	    //language:  'fr',
	    weekStart: 1,
	    todayBtn:  1,
	    autoclose: 1,
	    todayHighlight: 1,
	    startView: 2,
	    forceParse: 0,
	    showMeridian: 1,
	    startDate : d
	});
	$('#disableSelect').datetimepicker({
	    //language:  'fr',
	    weekStart: 1,
	    todayBtn:  1,
	    autoclose: 1,
	    todayHighlight: 1,
	    startView: 2,
	    forceParse: 0,
	    showMeridian: 1,
	    startDate : d
	});
</script>
@endpush